### ISSUE TITLE
T04: 2nd Iteration E/R Model

### ISSUE THREAD

**Issue by jjpulidos** [yasnair/Python_examples#4]
Use case:
- I would like to save my favorite songs
- I would like to check my liked songs
- I would like to check other users liked songs and other playlists
- Playlists should be Public or Private
- There should be 2 types of Playlists, 
    - Collaborative mode: Playlist which anyone can add songs
    - Non Collab mode: Only the creator can add/erase songs

DoD:
- Changes should be reflected on a new migration file on Alembic

Deadline:
- 25/01/2022

**Comment by yasnair** [comment]
Here the PR link -> https://github.com/yasnair/Python_examples/pull/9
